## IRIS; 사이킷런의 대표적 실습 데이터
### 붓꽃의 꽃받침, 꽃잎의 폭과 너비를 이용해서 붓꽃 품종을 예측

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
/content/iris.csv

![title](img/iriss.png)

https://scikit-learn.org/stable/datasets/index.html  
에서 다양한 데이터셋 확인이 가능하다

### 1. 데이터 로드

In [ ]:
import pandas as pd

from sklearn.datasets import load_iris

iris_dataset = load_iris()

### 2. 데이터 살펴보기

In [ ]:
type(iris_dataset)

sklearn.utils.Bunch

===========================================================  
Bunch; sklearn 에서 제공하는 데이터셋의 자료형

data: (필수) 독립 변수 ndarray 배열  
target: (필수) 종속 변수 ndarray 배열  
feature_names: (옵션) 독립 변수 이름 리스트  
target_names: (옵션) 종속 변수 이름 리스트  
DESCR: (옵션) 자료에 대한 설명
<br>
<br>
→ 일종의 딕셔너리형 구조라고 생각하면 이해하기 쉽다

===========================================================

In [ ]:
print("iris_dataset의 key 값:", iris_dataset.keys())

iris_dataset의 key 값: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
# print(iris_dataset['DESCR'])
print(iris_dataset['DESCR'][:500] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                

...


In [ ]:
print(iris_dataset['data'])  # 각각의 데이터 뽑아봄

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
print("iris_dataset의 feature_names 값:", iris_dataset['feature_names'])
print("iris_dataset의 target_names 값:", iris_dataset['target_names'])

iris_dataset의 feature_names 값: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
iris_dataset의 target_names 값: ['setosa' 'versicolor' 'virginica']


In [ ]:
# pandas 로 dataset 가져오기
print('iris dataset 의 data 값')

X_iris = pd.DataFrame(iris_dataset['data'])
X_iris.head(5)

iris dataset 의 data 값


0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

### 3. Local 에서 직접 data 를 불러오도록 하자

In [ ]:
iris = pd.read_csv('/content/iris.csv')  # csv 파일 불러오는 방법
iris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
# iris = pd.read_csv('iris.csv')  # csv 파일 불러오는 방법
# iris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

#### Data PreProcessing

##### 1. Split X and Y

In [ ]:
X_iris = iris[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]
y_iris = iris['variety']

Column 명을 변경

In [ ]:
# 컬럼명 변경 -> 'sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'
X_iris_columns = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
X_iris.columns = X_iris_columns
X_iris.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
y_iris

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [ ]:
y_iris.unique()  # 중복값 없이 출력   

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [ ]:
y_iris['variety'].unique()   # 위에 y_iris를 데이터 프레임으로 만들면 될 것임  # pd.DataFrame(~~~)

KeyError: ignored

### 3. Split train set, test set

In [ ]:
from pandas.core.common import random_state
# 함수를 이용해서 나누기
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_iris, y_iris, test_size = 0.3, random_state = 0)   # X는 데이터 y는 정답  # random_state = 0는 고정 시드값을 의미

### 4. Machine learning modeling

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)  # n_neighbors로 k를 정해줌/ 제일 가까운 것 뽑아내는 것

# n_neighbors는 k의 개수

### 5. Training

In [ ]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
60                 5.0               2.0                3.5               1.0
116                6.5               3.0                5.5               1.8
144                6.7               3.3                5.7               2.5
119                6.0               2.2                5.0               1.5
108                6.7               2.5                5.8               1.8
..                 ...               ...                ...               ...
9                  4.9               3.1                1.5               0.1
103                6.3               2.9                5.6               1.8
67                 5.8               2.7                4.1               1.0
117                7.7               3.8                6.7               2.2
47                 4.6               3.2                1.4               0.2

[105 rows x 4 columns]

In [ ]:
y_train

60     Versicolor
116     Virginica
144     Virginica
119     Virginica
108     Virginica
          ...    
9          Setosa
103     Virginica
67     Versicolor
117     Virginica
47         Setosa
Name: variety, Length: 105, dtype: object

### 데이터를 fit시키기   
- 훈련 데이터셋으로부터 모델을 만들려면 knn객체의fit 메서드를 사용한다.    
- 훈련 세트를 사용하여 분류 모델을 학습시킨다. KNeifhborsClassifer에서의 학습은 예측할 때 이웃을 찾을 수 있도록 데이터를 저장하는 것이다. 

  - x데이터는 여러 개의 차원으로 이루어진 배열,   y데이터는 레이블(각 점들의 분류 결과)가 된다.   


In [ ]:
## knn 알고리즘 traiging
knn.fit(X_train, y_train)  

KNeighborsClassifier(n_neighbors=3)

y_train = y_train.values.ravel() 의 코드는 (m,n)형태의 m*n개의 데이터를 한개의 (m*n,)시리즈 형태로 만드는 메소드입니다. input 데이터의 형식을 변경해주기위해서 작성하는 코드가 아닐까 생각합니다.

In [ ]:
print(y_train.shape)
print(y_train.values.ravel().shape)   # ravel() : 1차원으로 바꾸는 메소드 

# 참고 - flatten()으로 차원 바꾸는 법
# np.array(y_test).flatten()

(105,)
(105,)


In [ ]:
## knn 알고리즘 traiging
knn.fit(X_train, y_train.values.ravel())

KNeighborsClassifier(n_neighbors=3)

### 6. Predict

In [ ]:
import numpy as np

# 'sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)' 을 임의로 정한다
# 5.3, 2.1, 1.3, 0.2 의 수치로 정함
Our_X = np.array([[5.3, 2.1, 1.3, 0.2]])
Our_X

array([[5.3, 2.1, 1.3, 0.2]])

In [ ]:
# 임의의 데이터로 prediction
prediction = knn.predict(Our_X)
print("예측: {}".format(prediction))  


예측: ['Setosa']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


### 7. Accuracy

In [ ]:
y_pred = knn.predict(X_test)
print(y_pred.shape)
print("테스트 세트에 대한 예측값:\n {}".format(y_pred))

(45,)
테스트 세트에 대한 예측값:
 ['Virginica' 'Versicolor' 'Setosa' 'Virginica' 'Setosa' 'Virginica'
 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor' 'Virginica' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Setosa' 'Versicolor' 'Versicolor'
 'Setosa' 'Setosa' 'Virginica' 'Versicolor' 'Setosa' 'Setosa' 'Virginica'
 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Setosa' 'Virginica'
 'Versicolor' 'Setosa' 'Virginica' 'Virginica' 'Versicolor' 'Setosa'
 'Virginica' 'Versicolor' 'Versicolor' 'Virginica' 'Setosa' 'Virginica'
 'Setosa' 'Setosa']


In [ ]:
# y_test.shape

(45,)

In [ ]:
# flatten ->  y_test 를 1차원 matrix 로 변경
y_test_flatten = np.array(y_test).flatten()

In [ ]:
y_pred == y_test_flatten

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
print("테스트 세트의 정확도: {:.2f}".format(np.mean(y_pred == y_test_flatten)))  # True = 1, False = 0  -> 이것들을 다 더해서 평균 낸 것이 정확도 0.98

테스트 세트의 정확도: 0.98


In [ ]:
print("테스트 세트의 정확도: {:.2f}".format(knn.score(X_test, y_test_flatten)))

테스트 세트의 정확도: 0.98


In [ ]:
np.mean(y_pred == y_test_flatten)
knn.score(X_test, y_test_flatten)